---
- name: include distribution or OS Family variable
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure NTP-related packages are installed.
  tags: install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - tzdata

- name: Set timezone
  tags: config
  timezone:
    name: "{{ ntp_timezone }}"

- name: Ensure NTP is running and enabled as configured.
  tags: config
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled as configured.
  tags: config
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: no
  when: not ntp_enabled

- name: Generate ntp.conf file
  tags: config
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  when: ntp_manage_config
...
